# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# mysql:
#   image: my-mysql-image
#   environment:
#     MYSQL_ROOT_PASSWORD: mysecretpassword
#     MYSQL_USER: myuser
#     MYSQL_PASSWORD: mypassword
#     MYSQL_DATABASE: mydatabase
#   command: mysqld --bind-address=0.0.0.0 --skip-networking=0
#   ports:
#     - '3306:3306'

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

  apt_packages:
    - python3-dev
    - libmysqlclient-dev
    - apache2
    - apache2-dev
    - libapache2-mod-wsgi-py3
    - make
    - mysql-server
  # commands: # overwrites default build commands
  #   - sudo apt update && sudo apt install python3-dev libmysqlclient-dev apache2 apache2-dev libapache2-mod-wsgi-py3 make mysql-server -y && sudo service mysql start
  #   - sudo mysql -u root < setup.sql
  #   - echo -e "MYSQL_HOST=localhost\nMYSQL_USER=swob-user\nMYSQL_PASSWORD=swob-password\nMYSQL_DATABASE=swob-database" > .env
  #   - pip install -r requirements.txt && pip install -r sphinx/requirements.txt
  #   - cd sphinx && make extract-docs && cd ..
  jobs:
    post_checkout:
      - echo "Just a test, carry on ..."
    # pre_create_environment:
    #   - sudo apt update && sudo apt install python3-dev libmysqlclient-dev apache2 apache2-dev libapache2-mod-wsgi-py3 make mysql-server -y
    post_install:
      - service mysql start
    pre_install:
      - pip install python-dotenv
      - cd sphinx
      - echo -e "MYSQL_HOST=localhost\nMYSQL_USER=swob-user\nMYSQL_PASSWORD=swob-password\nMYSQL_DATABASE=swob-database" > .env
      - cd ..
      # - mysql -u root < sphinx/setup.sql
      # # get docker
      # - curl -fsSL https://get.docker.com -o get-docker.sh

      # # install docker
      # - sh get-docker.sh

      # # create docker group
      # - groupadd docker

      # # add user to group so as to run commands without root privileges
      # - usermod -aG docker $USER

      # # restart for changes to take effect
      # - systemctl reboot

      # # start docker daemon
      # - systemctl --user start docker.service

      # # download latest MySQL docker image
      # - docker pull mysql

      # # start MySQL docker container
      # docker run --name mysql-container -e MYSQL_ROOT_PASSWORD=mypassword -d mysql

      # # run sql script
      # - docker exec -i mysql-container mysql -u root -pmypassword < /path/to/sql-script.sql

    # - cd sphinx && make extract-docs && cd ..
    # post_build:
    # - service mysql stop

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: sphinx/docs/source/conf.py
# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
    - requirements: sphinx/requirements.txt
